### ISSUE TITLE
Ores pure are not displaying Silver

### ISSUE THREAD

**Issue by wokka1** [1337joe/du-factory-inventory#1]
I don't know how to do a pull request or I would, but line 49 of the ores display LUA needs to be changed from 
        {"Acanthite", {name = "Silver Pure", label = "Silver"}},
to 
        {"Acanthite", {name = "Pure Silver", label = "Silver"}},

Nice script!  Thanks

**Comment by 1337joe** [comment]
Thanks for submitting a ticket. I don't know when they changed it, but names are only checked on container scan so I wouldn't have noticed this until I had to build a new container databank.

This also affects all the other pures that were named with "Pure" second: Nickel, Silver, Fluorine, Scandium, Niobium, Vanadium

The fix is checked in. If any of the above don't show in your display after updating re-scan the container to pick up the new name in the databank.
